apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJaV2R2Y21KdmN6cG5hSEJmZWtoMlVXVnlTVmx1UmtOcFZVZHdabFJLWW5WR1pGRldUemc0Ym5CM01VRk9VRlIzIgoJCX0KCX0sCgkiY3VycmVudENvbnRleHQiOiAiY29saW1hIgp9
type: kubernetes.io/dockerconfigjson
